### ISSUE TITLE
Stack on death

### ISSUE THREAD

**Issue by Maxopoly** [DevotedMC/ExilePearl#15]
[22:00:51 ERROR]: Could not pass event PlayerDeathEvent to ExilePearl v0.5.3-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:409) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.EntityPlayer.die(EntityPlayer.java:409) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:911) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:772) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:500) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1585) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalArgumentException
        at net.minelink.ctplus.compat.v1_10_R1.NpcPlayerHelperImpl.getIdentity(NpcPlayerHelperImpl.java:84) ~[?:?]
        at com.devotedmc.ExilePearl.core.ExilePearlCore.getPlayerAsTaggedNpc(ExilePearlCore.java:505) ~[?:?]
        at com.devotedmc.ExilePearl.listener.PlayerListener.onEntityDeath(PlayerListener.java:522) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-850da7e-251a5b6]
        ... 22 more

**Comment by CivFactions** [comment]
Fixed
